Hardcoding qty for testing
 qty = [200000/float(position.current_price) if float(position.qty)*float(position.current_price) > 200000 else float(position.qty)]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?